
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dps?autoReconnection=true&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: qwe123!@#
        driver-class-name: com.mysql.cj.jdbc.Driver
        schema: classpath:insert.sql
        initialization-mode: always

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
