
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dps?autoReconnection=true&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: qwe123
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                #show_sql: true
                format_sql: true


logging.level:
    org.hibernate:
        SQL: debug
        type: trace